<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Search.Application\Search.Application.csproj" />
    <ProjectReference Include="..\Search.Domain\Search.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.5.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.2" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
  </ItemGroup>

   <ItemGroup>
	 <FrameworkReference Include="Microsoft.AspNetCore.App" />
   </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
