<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Grpc.Net.Client" Version="2.64.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductCatalog.Grpc\ProductCatalog.Grpc.csproj" />
    <ProjectReference Include="..\Search.Application\Search.Application.csproj" />
    <ProjectReference Include="..\Search.Domain\Search.Domain.csproj" />
    <ProjectReference Include="..\ProductCatalog.Contracts\ProductCatalog.Contracts.csproj" />
    <ProjectReference Include="..\Search.Api\Search.Api.csproj" />
  </ItemGroup>

</Project>